# Settings
safe: true
lsi: false

# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
current_version:  1.1.1
repo:             https://github.com/dotBunny/Hydrogen
repo_releases:	  https://github.com/dotBunny/Hydrogen/releases
repo_package:	  https://github.com/dotBunny/Hydrogen-Package
repo_fork:		  https://github.com/dotBunny/Hydrogen/fork

testflight_ios_version:	 		2.0.2
testflight_android_version:		1.2

asset_store:	  https://www.assetstore.unity3d.com/#/content/10311

download_source:  https://github.com/dotBunny/Hydrogen/archive/master.zip
download_dist:    https://github.com/dotBunny/Hydrogen-Package/archive/v1.1.0.zip


dotbunny:	      http://dotbunny.com
unityforge:		  http://unityforge.net

blog:             http://dotbunny.com/blog

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js